# Generated by Django 4.2.7 on 2024-01-01 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('totalPrize', models.CharField(blank=True, max_length=150, null=True)),
                ('holdingDate', models.DateTimeField(null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('supervisorName', models.CharField(blank=True, max_length=250, null=True)),
                ('newsSource', models.URLField(blank=True, max_length=250, null=True)),
                ('companyName', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, choices=[('operator', 'اپراتور'), ('bank', 'بانک'), ('car', 'خودرو'), ('store', 'فروشگاه'), ('shop', 'مغازه'), ('social media', 'شبکه اجتماعی')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('awaiting', 'در انتظار تایید'), ('approved', 'تایید شده'), ('disapproved', 'تایید نشده')], max_length=50, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('rank', models.SmallIntegerField(blank=True, null=True)),
                ('lottery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lottery.lottery')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoFile', models.FileField(upload_to='./uploaded_videos')),
                ('lottery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lottery.lottery')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=350, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsup', models.CharField(blank=True, max_length=50, null=True)),
                ('lottery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lottery.lottery')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureFile', models.ImageField(upload_to='./uploaded_images')),
                ('lottery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lottery.lottery')),
            ],
        ),
    ]
